apiVersion: v1
kind: Service
metadata:
  name: ping-prueba
  labels:
    app: ping-prueba
spec:
  selector:
    app: ping-prueba
  ports:
    - protocol: TCP
      port: 20200
      targetPort: 20200
  type: NodePort