name: Build and Push Docker Image to AWS ECR

## Ejecutamos por cada push
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      ## Checkout de la versi칩n actual del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      ## Configuramos las credenciales para conectarlos al AWS por medio del usuario AIM
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      ## ingresamos al registro
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      ## generamos la Imagen y la enviamos al registro correspondiente
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_URI }}
          IMAGE_TAG: latest
        ## ejecutamos los siguiente comandos
        run: |
          # Build the Docker image
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

          # Push the image to ECR
          docker push $ECR_REPOSITORY:$IMAGE_TAG

      - name: Instalar el YQ para actualizar el Manifiesto
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq
      - name: Get current datetime
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Actualizar el archivo deployment.yaml con la ultima versi칩n del docker
        run: |
          ## Actualizamos el Tag en el deployment usando el yq
          yq -i '.spec.template.spec.containers[0].image = "ping-prueba:$GITHUB_ENV"' ./k8s/k8s-deployment.yaml

      - name: Commit los cambios por el archivo de deploym,ent
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@noreply"
          git add k8s/k8s-deployment.yaml
          git commit -m 'Actualizaci칩n autom치tica'
          
          
          
          
          
      

          
